/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fastrobot_FastRobot */

#ifndef _Included_fastrobot_FastRobot
#define _Included_fastrobot_FastRobot
#ifdef __cplusplus
extern "C" {
#endif
#undef fastrobot_FastRobot_BUTTON1
#define fastrobot_FastRobot_BUTTON1 1L
#undef fastrobot_FastRobot_BUTTON2
#define fastrobot_FastRobot_BUTTON2 2L
#undef fastrobot_FastRobot_BUTTON3
#define fastrobot_FastRobot_BUTTON3 4L
/*
 * Class:     fastrobot_FastRobot
 * Method:    mouseMove
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_fastrobot_FastRobot_mouseMove
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     fastrobot_FastRobot
 * Method:    mousePress
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fastrobot_FastRobot_mousePress
  (JNIEnv *, jobject, jint);

/*
 * Class:     fastrobot_FastRobot
 * Method:    mouseRelease
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fastrobot_FastRobot_mouseRelease
  (JNIEnv *, jobject, jint);

/*
 * Class:     fastrobot_FastRobot
 * Method:    mouseWheel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fastrobot_FastRobot_mouseWheel
  (JNIEnv *, jobject, jint);

/*
 * Class:     fastrobot_FastRobot
 * Method:    keyPress
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fastrobot_FastRobot_keyPress
  (JNIEnv *, jobject, jint);

/*
 * Class:     fastrobot_FastRobot
 * Method:    keyRelease
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fastrobot_FastRobot_keyRelease
  (JNIEnv *, jobject, jint);

/*
 * Class:     fastrobot_FastRobot
 * Method:    getPixelColor
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_fastrobot_FastRobot_getPixelColor
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     fastrobot_FastRobot
 * Method:    getScreenPixels
 * Signature: (IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_fastrobot_FastRobot_getScreenPixels
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     fastrobot_FastRobot
 * Method:    getScreenWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fastrobot_FastRobot_getScreenWidth
  (JNIEnv *, jobject);

/*
 * Class:     fastrobot_FastRobot
 * Method:    getScreenHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fastrobot_FastRobot_getScreenHeight
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
