/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fastrobot_UltraFastRobot */

#ifndef _Included_fastrobot_UltraFastRobot
#define _Included_fastrobot_UltraFastRobot
#ifdef __cplusplus
extern "C" {
#endif
#undef fastrobot_UltraFastRobot_BUTTON1
#define fastrobot_UltraFastRobot_BUTTON1 1L
#undef fastrobot_UltraFastRobot_BUTTON2
#define fastrobot_UltraFastRobot_BUTTON2 2L
#undef fastrobot_UltraFastRobot_BUTTON3
#define fastrobot_UltraFastRobot_BUTTON3 4L
/*
 * Class:     fastrobot_UltraFastRobot
 * Method:    mouseMoveInstant
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_fastrobot_UltraFastRobot_mouseMoveInstant
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     fastrobot_UltraFastRobot
 * Method:    mousePressInstant
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fastrobot_UltraFastRobot_mousePressInstant
  (JNIEnv *, jobject, jint);

/*
 * Class:     fastrobot_UltraFastRobot
 * Method:    mouseReleaseInstant
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fastrobot_UltraFastRobot_mouseReleaseInstant
  (JNIEnv *, jobject, jint);

/*
 * Class:     fastrobot_UltraFastRobot
 * Method:    mouseWheelInstant
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fastrobot_UltraFastRobot_mouseWheelInstant
  (JNIEnv *, jobject, jint);

/*
 * Class:     fastrobot_UltraFastRobot
 * Method:    keyPressInstant
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fastrobot_UltraFastRobot_keyPressInstant
  (JNIEnv *, jobject, jint);

/*
 * Class:     fastrobot_UltraFastRobot
 * Method:    keyReleaseInstant
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fastrobot_UltraFastRobot_keyReleaseInstant
  (JNIEnv *, jobject, jint);

/*
 * Class:     fastrobot_UltraFastRobot
 * Method:    keySequence
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_fastrobot_UltraFastRobot_keySequence
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     fastrobot_UltraFastRobot
 * Method:    getPixelColorInstant
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_fastrobot_UltraFastRobot_getPixelColorInstant
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     fastrobot_UltraFastRobot
 * Method:    getScreenPixelsDirect
 * Signature: (IIII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_fastrobot_UltraFastRobot_getScreenPixelsDirect
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     fastrobot_UltraFastRobot
 * Method:    setupScreenBuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_fastrobot_UltraFastRobot_setupScreenBuffer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     fastrobot_UltraFastRobot
 * Method:    updateScreenBuffer
 * Signature: (IIII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_fastrobot_UltraFastRobot_updateScreenBuffer
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     fastrobot_UltraFastRobot
 * Method:    getScreenWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fastrobot_UltraFastRobot_getScreenWidth
  (JNIEnv *, jobject);

/*
 * Class:     fastrobot_UltraFastRobot
 * Method:    getScreenHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fastrobot_UltraFastRobot_getScreenHeight
  (JNIEnv *, jobject);

/*
 * Class:     fastrobot_UltraFastRobot
 * Method:    batchMouseOperations
 * Signature: ([[I)V
 */
JNIEXPORT void JNICALL Java_fastrobot_UltraFastRobot_batchMouseOperations
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     fastrobot_UltraFastRobot
 * Method:    getPixelColorsBatch
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_fastrobot_UltraFastRobot_getPixelColorsBatch
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
